### ISSUE TITLE
Brainstorm

### ISSUE THREAD

**Issue by jonathandw743** [stupxd/Blueprint#1]
Sorry for using issues perhaps inappropriately.

If I were to make a version of this for brainstorm, would you accept a pull request into this project, or prefer me to fork? If forking is preferable, do I have your permission to use a lot of your code (as this project doesn't have a license).

**Comment by stupxd** [comment]
It's fine, I don't mind either. I'm open for a PR, but if you want to make a fork or your own version - feel free to do so. If I remember I'll add a license at some point but it's probably going to be GPL.

Brainstorm version would be cool, it's something that's been suggested a lot but I'm not entirely sure how to tackle it properly - I was thinking of using a shader to isolate joker outline and combining it with plain brainstorm texture. Though it is easier said than done and I didn't have much free time & motivation to start working on that lately 😦

**Comment by jonathandw743** [comment]
![brainstormbg](https://github.com/user-attachments/assets/c5bc3b7d-70e2-4393-aeca-3badc02f164b)
https://www.shadertoy.com/view/4fKfDD
![Screenshot from 2024-12-13 23-02-30](https://github.com/user-attachments/assets/bf4c8e4b-34fa-4e90-8e29-c3bd767b6919)
Something like this?
